### ISSUE TITLE
你好作者

### ISSUE THREAD

**Issue by li9hu** [glzjin/20190511_awd_docker#1]
你好，我是一名ctf爱好者。请教一下为什么我导入你的镜像后网页还是访问不了呢
用的是我的阿里云，然后第一次使用docker 和dockers-compose 百度了差不明。。
ps 还是新手，望大佬指点一下
此致敬礼！
盼复

**Comment by glzjin** [comment]
Hello，请问你可以发一下 docker ps 的结果截图吗？

**Comment by li9hu** [comment]
这是安装过程中出现的红了一片(docker-compose up -d --build)
![WP3ETJZU(QUXJA{VOSIK EQ](https://user-images.githubusercontent.com/48636077/58058029-e2651980-7b99-11e9-9824-0f6af2e9efb3.png)
这是docker ps -a 的结果
![S~8 U)GB4L N$M~}MVYY8MI](https://user-images.githubusercontent.com/48636077/58058049-f446bc80-7b99-11e9-90e4-66091cfd7ccb.png)
网页无法打开
![Uploading BQZYIXU3B@6P5IW7G5U9~MD.png…]()
端口情况
![R(V9`$2BSM4E2F8QLHB5UEE](https://user-images.githubusercontent.com/48636077/58058078-10e2f480-7b9a-11e9-9b0a-ce4ebc768fb8.png)

感谢作者回复

**Comment by glzjin** [comment]
看起来容器都正常运行了，请问你访问的是哪个端口呢？

**Comment by li9hu** [comment]
我的是映射的是80端口，浏览器*.*.*.*:80 可以访问我自己的网页 :1889* 都无法访问。。防火墙也关掉了

**Comment by glzjin** [comment]
你应该访问 18889~18895 端口。一个靶机有一个 HTTP 端口，一个 SSH 端口。

**Comment by li9hu** [comment]
我查看了文件， 端口没有输入错，而且ssh端口也连接不上。 很郁闷.

**Comment by glzjin** [comment]
不是80，是18889之类的端口 你看开放的端口号-.-


来自阿里邮箱 iPhone版
 ------------------原始邮件 ------------------
发件人：MrManatee <notifications@github.com>
日期：2019-05-21 11:40:04
收件人：glzjin/20190511_awd_docker <20190511_awd_docker@noreply.github.com>
抄送：glzjin <glzjin@zhaojin97.cn>, Comment <comment@noreply.github.com>
主题：Re: [glzjin/20190511_awd_docker] 你好作者 (#1)
我查看了文件， 端口没有输入错，而且ssh端口也连接不上。 很郁闷.

**Comment by li9hu** [comment]
你好！问题解决了，是因为阿里云防火墙的原因，需要在控制台添加规则。

再次感谢作者的回信。

**Comment by li9hu** [comment]
还有一个事情想请教，为什么我部署好后，我服务器的根目录会生成webflag的文件夹？宿主机不是和容器分开的吗

**Comment by li9hu** [comment]
还有一个事情想请教，为什么我部署好后，我服务器的根目录会生成webflag的文件夹？宿主机不是和容器分开的吗

**Comment by glzjin** [comment]
里面内容是啥-.-？按理来说不会有的


来自阿里邮箱 iPhone版
 ------------------原始邮件 ------------------
发件人：MrManatee <notifications@github.com>
日期：2019-05-21 14:12:44
收件人：glzjin/20190511_awd_docker <20190511_awd_docker@noreply.github.com>
抄送：glzjin <glzjin@zhaojin97.cn>, Comment <comment@noreply.github.com>
主题：Re: [glzjin/20190511_awd_docker] 你好作者 (#1)
还有一个事情想请教，为什么我部署好后，我服务器的根目录会生成webflag的文件夹？宿主机不是和容器分开的吗

**Comment by li9hu** [comment]
在自己的虚拟上弄好了！做了一下题目，大佬查看日志是通过那个run.py吗，还有一个log.php

**Comment by glzjin** [comment]
查日志还可以看nginx和Apache的访问日志


来自阿里邮箱 iPhone版
 ------------------原始邮件 ------------------
发件人：MrManatee <notifications@github.com>
日期：2019-05-23 18:55:24
收件人：glzjin/20190511_awd_docker <20190511_awd_docker@noreply.github.com>
抄送：glzjin <glzjin@zhaojin97.cn>, Comment <comment@noreply.github.com>
主题：Re: [glzjin/20190511_awd_docker] 你好作者 (#1)
Closed #1.
